version: '3'
services:
  app:
    build: .
    container_name: node_app
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis01:6379
    depends_on:
         - redis
    command: npm start

  redis:
    image: redis/redis-stack:latest
    container_name: redis01
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - "C:/Users/jairi/OneDrive/Documentos/TECNOLOGICO/Semestre 9/NoSQL/redis db/redis_data:/data"